name: CI
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@v2

      - name: build
        env:
          USER: ${{ secrets.SERVER_USER }}
          TARGET: ${{ secrets.SERVER_PATH }}
          KEY: ${{ secrets.SERVER_KEY }}
          DOMAIN: ${{ secrets.SERVER_DOMAIN }}
        run: |
          mkdir ~/.ssh
          echo "$KEY" | tr -d '\r' > ~/.ssh/idkey
          chmod 400 ~/.ssh/idkey
          eval "$(ssh-agent -s)"
          ssh-add ~/.ssh/idkey
          ssh-keyscan -H $DOMAIN >> ~/.ssh/known_hosts
          scp -r * $USER@$DOMAIN:$TARGET